### PR TITLE
Update suite.yml for v1.11.1+suite.1

### LINKED ISSUE #194: Create a new v1.11.1+dap.1 suite release

### LINKED ISSUE #199: Add target="_blank" to GitHub links in HTML output
We'd like our HTML docs to open GitHub links in a new window. In this issue, we'd like to update the HTML template to add `target="_blank"` to all GitHub links (and ideally any link that doesn't refer to a subpage at docs.conjur.org or docs.cyberark.com) so that the link will open in a new window.

### PR DESCRIPTION
**Pull request by izgeri**
### What does this PR do?
- Preps for v1.11.1+suite.1 release
- Fixes test failure that came from a change to real release notes

### What ticket does this PR close?
Resolves #194 

Release checklist: https://github.com/cyberark/conjur-oss-suite-release/wiki/v1.11.1-suite.1
Draft release notes: https://gist.github.com/izgeri/0a60f26246decfdcac8fe1c5e3856abf
Early draft of docs output: [ConjurSuite.htm.zip](https://github.com/cyberark/conjur-oss-suite-release/files/5637762/ConjurSuite.htm.zip) - ~would like to resolve #199 before creating actual docs HTML~ - there is one manual change required to the docs link in the upgrade instructions section (so it won't pop up in a new window).

#### Release PRs
**If you are preparing for a release**, are the following items complete?
- [x] The PR title / description clearly state the suite release version.
- [x] The [Jenkins dashboard](https://jenkins.conjur.net/view/OSS%20Suite%20Components/) shows no ongoing
      build failures for any included components.
- [x] The PR includes a link to a markdown release notes draft - this can be
     generated by running:
     ```
     summon -p keyring.py   --yaml 'GITHUB_TOKEN: !var github/api_token' \
       ./parse-changelogs \
       -v {suite-version} \
       -t release
       -o RELEASE_NOTES.md
     ```
- [x] The PR includes PM-approved "What's new" text.

### CODE REVIEW

**Review by alexkalish — CHANGES_REQUESTED** [review]
## Questions/Comments about the Release Notes
### Conjur
1. Is the UBI Conjur image public in the Red Hat registry?  I cannot find it.  If it's not published, I don't think we should release the suite, as it's part of the CL.  Also, we'll need a doc ticket to add a link to it [here](https://docs.conjur.org/Latest/en/Content/OSS/Installation/DockerCompose.htm).
2. The OSS docs do not seem to include GCP Function support.  @izgeri, did you say this wasn't going to be included?  The CL states that it is included.  How can we square this?

### K8s Authenticator Client
1. Several nice debug/troubleshooting changes were made by @orenbm, but I cannot find any documentation about how to use them.  We need to this added for OSS and enterprise, minimally in the repo for the release.  I don't know this component well enough to author the doc issue.  @orenbm: could you please write up some basic troubleshooting info related to the changes here?  I'm happy to get them into the technical writer queue for docs.

**Comment by izgeri** [comment]
@alexkalish - re: your points above.

**Conjur**

1. The image isn't public yet, though I hope it will be public by the time we publish this release. It shouldn't be added to the page you linked (which is for Docker Compose) - when it's ready to be used (i.e. when cyberark/conjur-oss-helm-chart#113 is complete) it will be referenced from the helm chart docs.
2. I've updated the release docs ticket to ask that the GCP cloud function authentication docs be published at the same time as the suite release notes are published (the docs are already written, they are just in "do not publish" mode until the software is released).

**K8s authn**

1. There is a [docs ticket](https://github.com/cyberark/conjur-docs/issues/1225) to add a troubleshooting related to the changes you're referencing - I've also added it to the release docs ticket so that it will be published with these release notes.

**Review by alexkalish — APPROVED** [review]
Confirmed that version bumps since last review have good CL entries and docs.

**Comment by izgeri** [comment]
**Draft "What's New" Content**

# DRAFT - ready for comments 
---

# What's New
This Suite release aligns with Conjur Server [version 1.11.1](https://github.com/cyberark/conjur/releases/tag/v1.11.1). It includes quality and troubleshooting improvements to the Conjur SDK, as well as enhancements in the Conjur Kubernetes and Google Cloud Platform authenticators. Notable updates are highlighted below.

For a reminder of the Conjur Open Source Suite Release structure please refer to the documentation [introduction](https://docs.conjur.org/Latest/en/Content/Overview/Conjur-OSS-Suite-Overview.html?tocpath=_____1#StructureofConjurOpenSourceSuite).

## Conjur Core

#### Deployment and Upgrades

The [Helm Chart](https://github.com/cyberark/conjur-oss-helm-chart/tree/master/conjur-oss) is updated to support strings for image tag values. Previously, only numeric values were allowed, but this could lead to semantic versions provided in the form `{major}.{minor}`, where `{minor}` is a multiple of 10, being interpreted as decimal values and truncating the final `0`. With this change, the helm chart can now accept non-numeric image tag values such as `latest`.

#### Conjur API

Conjur now raises an Unauthorized error when a user attempts to rotate the API key of a nonexistent role. Previously, the operation would result in a successful rotation of the _user's_ API key, with no indication that the target of the operation had changed. 

#### *NEW* Google Cloud Platform (GCP)f Support for Google Cloud Functions

Google Cloud Function (GCF) applications can now authenticate to Conjur using the GCP authenticator. For more information on how to get started using this new feature, reference the [GCP authenticator documentation](https://docs.conjur.org/Latest/en/Content/Operations/Services/cjr-gcp-authn.htm).

#### Kubernetes Authenticator

When the Conjur Kubernetes authenticator encounters an error while injecting the authentication certificate into the client container, it now writes the error message into a file in the client container at the path `/tmp/conjur_set_file_content.log`. Together with the changes in the Kubernetes authenticator client available in this release, this allows for easier troubleshooting of certificate injection issues.

## Conjur Integrations

#### Kubernetes Authentication client

As noted above, with this release the Conjur Kubernetes authenticator has been updated to write error messages due to problems in the certificate injection process into a file in the container at the path `/tmp/conjur_set_file_content.log`. With this release, the authenticator client has also been updated so that if it cannot read the certificate file within 10 seconds, it will attempt to log the contents of the error log file to the authenticator client container logs. This makes it possible to observe all Kubernetes authentication steps when experiencing issues during the certificate injection process by reviewing the client container logs and the Conjur server logs.

In addition, the authenticator container logs have been updated to make the default log level less verbose and make errors more obvious. Detailed logs are enabled by setting the `DEBUG=true` environment variable on the authenticator container. 

Previously, log entries included a timestamp with precision in seconds. For example: “2020/09/15 08:50:21”. Now, log entries have a timestamp with microsecond precision. For example: “2020/09/15 08:50:21.682962”. The additional precision enhances observability of multiple events that occur within a single second.  

Further, the authenticator client log prefixes are updated to remove the log level suffix from the log message codes (e.g. CAKC001E -> CAKC001). Existing monitors or alerts on these code need to be updated. 

#### Secrets Provider for Kubernetes

Secrets Provider for Kubernetes has been updated to use the Kubernetes authenticator client v0.19.0. With this change, users benefit from the changes made to the Kubernetes authenticator client in this release for improved performance and troubleshooting capabilities during the client certificate injection process.

## Secrets Delivery

#### Secretless Broker

Secretless Broker's Conjur secret provider has been updated to use the Kubernetes authenticator client v0.19.0 so that when using Secretless with the Conjur Kubernetes authenticator, users may also benefit from improved performance and troubleshooting capabilities during the client certificate injection process.

## Deprecations

Support for OpenShift versions 3.9 and 3.10 will be officially deprecated with the next suite release.  These versions have already been declared end of life by Red Hat and were deprecated by CyberArk Dynamic Access Provider in version 11.7. Users are encouraged to upgrade their OpenShift clusters to at least version 3.11, which is supported by both Red Hat and the Conjur OSS Suite.

**Comment by boazmichaely** [comment]
@izgeri Thanks for taking the lead here !
some comments / questions

I would consider the following as bugs rather than news.
In the CyberArk release notes (RN) we focus What's New (WN) on significant value. Bugs are listed in another  section. In OSS case the bugs would hopefully be covered by respective changelogs. Let's assess that, and if the are articulated as clearly as you have here then these would be bugs rather than news:
- helm chart with strings 
- Conjur API Unauthorized error (BTW which bug does this refer to in the RN ? Is this not a security related issue?

*** WIP  saving for draft   I'll erase this linme when done ***

**Comment by izgeri** [comment]
@boazmichaely I updated the draft based on your feedback, and reviewed the [12.0 RRN](https://pcloudsandbox.azurewebsites.net/Product-Doc/OnlineHelp/PAS/Latest/en/Content/Release%20Notes/RN-WhatsNew12-0.htm) to make sure the language we've used here is consistent. There are some slight tweaks I've made to remove some ambiguity in the text given the way we have the information organized here.

Note that for the API / helm chart changes I removed, there are changelog entries that cover the removed text. In particular for the helm chart, the change log says:
> Image tag values must now include surrouding quotes when they are set in a values.yaml file. Arbitrary tag strings are allowed now (e.g. "latest" is allowable).

and for the API change, the change log says:
> Conjur now raises an Unauthorized error when a user attempts to rotate the API key of a nonexistent role. Previously, the operation would result in a successful rotation of the existing user's API key, with no indication that the target of the operation had changed.

**Comment by boazmichaely** [comment]
@izgeri (CC @alexkalish, others ) let's separate getting 1.11.1 out and learning from our mistakes.
I'll start with the latter.
## 1. going forward
- We have suffered from lack of communication about the source of truth for existing release notes as that SOT moves up over time from the AAM Rolling Release notes (RRN) through the  PAS release notes in WORD, to the final version in Flare.  That SOT includes both What's New (WN) and specific bug description
- How do we minimize the confusion ? 
  - Bugs:  When we review bug fix text, can the modified text be updated back into  the changelog?
  - WN: Where should we store the SOT and keep track of common OSS/DAP features to know what was published when ? 

## 2. this release
- Feels like the description for the `Kubernetes Authentication client` does not belong here. It should be captured in docs and we should make a high level statement here with reference to the doc link.
A high level could be:

  The Conjur Kubernetes Authentication now better handles delays in internal communication between the  Kubernetes Authentication Client and Conjur, and the logs now provides a better view of that communication. In addition several enhancements were made to the log.See `CHANGELOG1 , CHANGELOG2`  for specific changes to the log and to `DOC  LINK` for detailed documentation.

@izgeri  WDYT? Can we move those descriptions back into the respective changelogs ?

**Review by boazmichaely — APPROVED** [review]
@izgeri  I approve the "what's new", thanks

**Pull request merged**
