### PR TITLE
Suite updates for v1.10.0+suite.1 release

### LINKED ISSUE #187: There is a v1.10.0+suite.1 release of the Conjur OSS suite

### PR DESCRIPTION
**Pull request by izgeri**
### What does this PR do?
The suite.yml is updated to prepare for v1.10.0+suite.1 release.

TODO checklist:
- [x] Update Ruby client version
- [ ] ~Fix Golang client - cyberark/conjur-api-go#78, cyberark/conjur-api-go#80~
- [x] Update helm chart version
- [x] Add release description

### What ticket does this PR close?
Resolves #187 

#### Change log
- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [x] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [x] This PR does not require updating any documentation

### CODE REVIEW

**Comment by izgeri** [comment]
Note: this is currently blocked by a Ruby client build failure (https://github.com/cyberark/conjur-api-ruby/issues/181)

**Review by alexkalish — CHANGES_REQUESTED** [review]
Just two requested changes:

- [ ] Remove Summon providers, as this suite is focused on Conjur as the the provider of secrets.  Nonetheless, they are still important parts of our OSS portfolio of projects.
- [x] Fix the obviously unhelpful changelog entry in the Java client (i.e `Implemented #74`).

**Comment by izgeri** [comment]
Link to draft release notes: https://gist.github.com/izgeri/2c6e97c6bc22f1c127f79cc70a641379
Release wiki page: https://github.com/cyberark/conjur-oss-suite-release/wiki/v1.10.0-suite.1

**Comment by boazmichaely** [comment]
# THIS IS WIP - I just saved it here  for now so it won't get lost
---

# What's new in Conjur Open source Suite Release
This Suite release aligns with Conjur Server [version 1.10](https://github.com/cyberark/conjur/releases/tag/v1.10.0). 
It brings together a wealth of updates published since our first Suite release back in March, across Conjur Core, Conjur Integrations,  Secrets Delivery and exciting new build tools!

## Installation and Deployment
Using the updated [Helm Chart](https://github.com/cyberark/conjur-oss-helm-chart/tree/master/conjur-oss)  Conjur can now be built into a Kubernetes environment as a persistent system so that the Postgres database contents are preserved across pod resets. You can now upgrade a production deployment and you can rotate SSL certificates. The resulting system is more secure and more robust than before.  
Experiment with Conjur on your laptop running KinD and leverage the demo scripts included in the [examples](https://github.com/cyberark/conjur-oss-helm-chart/blob/master/examples/kubernetes-in-docker/README.md) folder ! 

## Conjur Server
#### FIPS-140  (CHECK THIS)
Conjur OSS can be configured to run in FIPS compliant or Non-FIPS compliant mode (XXX how ?)  
#### Updates
Between Conjur server version 1.5 and 1.10 the Conjur server has made updates to underlying 3rd party libraries, resolved a few  security issues and fixed a number of issues

## Google Cloud Native Authentication
(mention  support in the Conjur Server , the clients and annotations. Point to docs)

**Comment by izgeri** [comment]
@boazmichaely here is my proposed "What's New" draft. Notably, I cut out OSS FIPS support (I don't know that this has been looked at, so I think we should drop it until we are ready to announce that) and the GCP authenticator (which is not yet documented).

I think even as trimmed-down as this is, we could still edit it further / improve the clarity of what is here.

---

## What's New

This Suite release aligns with Conjur Server [version 1.10](https://github.com/cyberark/conjur/releases/tag/v1.10.0). 
It brings together a wealth of updates published since our [first Suite release](https://docs.conjur.org/Latest/en/Content/ReleaseNotes/ConjurOSS-suite-v1.5.0-s1.htm)
in June. For a reminder of the Conjur Open Source Suite Release structure please refer to
the documentation [introduction](https://docs.conjur.org/Latest/en/Content/Overview/Conjur-OSS-Suite-Overview.html?tocpath=_____1#StructureofConjurOpenSourceSuite).

### Conjur Server Enhancements

#### Deployment and Upgrades

Using the updated [Helm Chart](https://github.com/cyberark/conjur-oss-helm-chart/tree/master/conjur-oss),
Conjur can be deployed into a Kubernetes environment as a persistent system so that the Postgres database
contents are preserved across pod resets. You can now upgrade a production deployment, and you can rotate SSL certificates.  
You can now also experiment with Conjur on your laptop running KinD and using the demo scripts included in the [examples](https://github.com/cyberark/conjur-oss-helm-chart/blob/master/examples/kubernetes-in-docker/README.md) folder! 

#### *NEW* Azure Native Authentication 

The [Conjur Azure Authenticator](https://docs.conjur.org/Latest/en/Content/Operations/Services/azure_authn.htm)
is a highly secure method for authenticating Azure workloads to Conjur using their underlying Microsoft Azure
identity. Please refer to the [documentation](https://docs.conjur.org/Latest/en/Content/Operations/Services/azure_authn.htm#SupportedAzureservices)
for the latest list of the supported Azure Services.

#### Other Conjur Server Updates
Between Conjur OSS Suite release 1.5 and 1.10, the Conjur server has made updates to underlying 3rd party
libraries, resolved a few security issues, and fixed a number of bugs

### Conjur SDK Enhancements

#### Conjur Java Client Library

You can now include the Conjur Java client library in your Java code using its published [Maven releases](https://mvnrepository.com/artifact/com.cyberark.conjur.api/conjur-api)!
This greatly improves the usability of the Conjur Java client, which used to require building from source.
The Java client also now supports setting a custom `javax.net.ssl.SSLContext` for configuring the TLS connection
to the Conjur server, making it easier to establish trust between your client and the Conjur server. Please
see the [documentation](https://github.com/cyberark/conjur-api-java) for more details and instructions
on how to get started.

### Conjur Integrations Enhancements

#### Puppet integration
The Conjur Puppet module has been enhanced and Puppet version 6 is now supported for both Windows and Linux.
Puppet 6 introduced Deferred Functions, a feature that was designed specifically to enable fetching secrets
by the Puppet agent at runtime. By leveraging this feature, the Conjur Puppet module now enjoys a simpler and
more effective flow. In addition, with the latest release of the Conjur Puppet module, it now seamlessly works
with multiple Puppet compile masters, enabling organizations to support high scale Puppet deployments.

**Note:** In this release, support for using the Conjur Puppet module with Conjur Enterprise v4 and with native
support for host factory tokens was removed.

### Secrets Delivery

#### Secrets Provider for Kubernetes

To simplify and better support large deployments, the Secrets Provider for Kubernetes can now run in its own pod as
a standalone application and serve multiple applications. A new Helm chart is offered for easy
[deployment](https://docs.conjur.org/Latest/en/Content/Integrations/k8s-ocp/cjr-k8s-secrets-provider-ac.htm#SetuptheSecretsProviderforKubernetesapplicationcontainer).

In addition, the CyberArk Kubernetes Secrets provider is also available as a [Red Hat certified container image](https://catalog.redhat.com/software/containers/search?q=cyberark).

#### Secretless Broker

Secretless Broker added support for the `verify-full` SSL mode to enable SSL host name validation for the
[MySQL](https://docs.conjur.org/Latest/en/Content/References/connectors/scl_mysql.htm)
and [PostgreSQL](https://docs.conjur.org/Latest/en/Content/References/connectors/scl_postgres.htm) connectors.
The Secretless Generic HTTP Connector (which is still in _beta_) was updated to support target services that
use self-signed certificates, and support was added for injecting credentials via
[query parameters](https://github.com/cyberark/secretless-broker/blob/master/internal/plugin/connectors/http/generic/README.md#queryparams). The Secretless Generic HTTP Connector was also updated to support
configuring Secretless to communicate with APIs that use [OAuth1](https://github.com/cyberark/secretless-broker/blob/master/internal/plugin/connectors/http/generic/README.md#oauth1)
for authentication.

To learn more about the Generic HTTP Connector, please see the **new** [example generic connector configurations](https://github.com/cyberark/secretless-broker/tree/master/examples/generic_connector_configs)
that are now available in the Secretless project. These sample Secretless configurations enable out-of-the-box support
for a broad set of popular APIs and API authentication schemes, such as OAth1, OAth2, Docker Registry, ElasticSearch, ServiceNow, Splunk and many others. They also serve as an example for writing HTTP connectors to other APIs.

**Comment by boazmichaely** [comment]
@izgeri 

- Thanks for the Java write-up and simplifications.
- I see the value in organizing by topics but I'd still like to try the Suite structure: It's a new concept and we need to be consistent in how we walk people through it. If our structure is confusing then let's fix that.  We should ask the community for feedback - we don't know if people understand this whole Suite thing at all.
- I've trimmed it down further a bit (but added some points back). Specifically the K8s authn client only to mention the Red Hat container image. 
- I'm not sure about weaving End-of-Support inline as opposed to its own section, but I guess you're thinking automation going forward so I left it as you did.
- Let's finalize GCP authenticator today. It was planned for inclusion , let's try to make it (I added it back in)
- Fixed the` <CR><LF>` issues

---

# What's New

This Suite release aligns with Conjur Server [version 1.10](https://github.com/cyberark/conjur/releases/tag/v1.10.0).
It brings together a wealth of updates published since our [first Suite release](https://docs.conjur.org/Latest/en/Content/ReleaseNotes/ConjurOSS-suite-v1.5.0-s1.htm) in June, across **Conjur Core**, **Conjur Integrations**, and **Secrets Delivery**. For a reminder of the Conjur Open Source Suite Release structure please refer to the documentation [introduction](https://docs.conjur.org/Latest/en/Content/Overview/Conjur-OSS-Suite-Overview.html?tocpath=_____1#StructureofConjurOpenSourceSuite).

## Conjur Core

#### Deployment and Upgrades

Using the updated [Helm Chart](https://github.com/cyberark/conjur-oss-helm-chart/tree/master/conjur-oss),  Conjur can be deployed into a Kubernetes environment as a persistent system so that the Postgres database contents are preserved across pod resets. You can now upgrade a production deployment, and you can rotate SSL certificates.  
You can now also experiment with Conjur on your laptop running KinD and using the demo scripts included in the [examples](https://github.com/cyberark/conjur-oss-helm-chart/blob/master/examples/kubernetes-in-docker/README.md) folder! 

#### *NEW* Azure Native Authentication 

The [Conjur Azure Authenticator](https://docs.conjur.org/Latest/en/Content/Operations/Services/azure_authn.htm) is a highly secure method for authenticating Azure workloads to Conjur using their underlying Microsoft Azure identity. Please refer to the [documentation](https://docs.conjur.org/Latest/en/Content/Operations/Services/azure_authn.htm#SupportedAzureservices) for the latest list of the supported Azure Services.

#### *NEW* Google Cloud Native Authentication 
The Conjur GCP authenticator `XXX NEED REFERENCE TO DOCS`is a highly secure method for authenticating Google Cloud workloads to Conjur using their underlying Google Cloud identity. 
Supported Google Cloud services include :
* Compute Engine
* Cloud Functions

#### Conjur Java Client Library

You can now include the Conjur Java client library in your Java code using its published [Maven releases](https://mvnrepository.com/artifact/com.cyberark.conjur.api/conjur-api)!
This greatly improves the usability of the Conjur Java client, which used to require building from source.
The Java client now also makes it easier to establish trust between your client and the Conjur server when configuring the TLS connection.
Please see the [documentation](https://github.com/cyberark/conjur-api-java) for more details and instructions on how to get started.

## Conjur Integrations

#### Secrets Provider for Kubernetes

* To simplify and better support large deployments, the Secrets Provider for Kubernetes can now run in its own pod as a standalone application and serve multiple applications. A new Helm chart is offered for easy [deployment](https://docs.conjur.org/Latest/en/Content/Integrations/k8s-ocp/cjr-k8s-secrets-provider-ac.htm#SetuptheSecretsProviderforKubernetesapplicationcontainer).
* More complex secrets are supported other than plaintext user name and password . This includes JSON structures and SSH keys. 

The CyberArk Kubernetes Secrets provider is also available as a [Red Hat certified container image](https://catalog.redhat.com/software/containers/search?q=cyberark).

#### Kubernetes Authentication client
The CyberArk  Kubernetes (OpenShift) Authentication client is also available as a [Red Hat certified container image](https://catalog.redhat.com/software/containers/search?q=cyberark)

#### Puppet integration
The Conjur Puppet module has been enhanced and Puppet version 6 is now supported for both Windows and Linux.
Puppet 6 introduced Deferred Functions, a feature that was designed specifically to enable fetching secrets by the Puppet agent at runtime. By leveraging this feature, the Conjur Puppet module now enjoys a simpler and more effective flow. 
In addition, it now seamlessly works with multiple Puppet compile masters, enabling organizations to support high scale Puppet deployments.

**Note:** In this release, support for using the Conjur Puppet module with Conjur Enterprise v4 and with native
support for host factory tokens was removed.


## Secrets Delivery

#### Secretless Broker

* Secretless Broker added support for the `verify-full` SSL mode to enable SSL host name validation for the [MySQL](https://docs.conjur.org/Latest/en/Content/References/connectors/scl_mysql.htm) and [PostgreSQL](https://docs.conjur.org/Latest/en/Content/References/connectors/scl_postgres.htm) connectors.
* The Secretless Generic HTTP Connector (which is still in _beta_) was updated to support target services that use self-signed certificates, and support was added for injecting credentials via [query parameters](https://github.com/cyberark/secretless-broker/blob/master/internal/plugin/connectors/http/generic/README.md#queryparams). 
* The Generic HTTP Connector was also updated to support configuring Secretless to communicate with APIs that use [OAuth1](https://github.com/cyberark/secretless-broker/blob/master/internal/plugin/connectors/http/generic/README.md#oauth1) for authentication.
  To learn more about the Generic HTTP Connector, please see the **new** [example generic connector configurations](https://github.com/cyberark/secretless-broker/tree/master/examples/generic_connector_configs). These sample Secretless configurations enable out-of-the-box support for a broad set of popular APIs and API authentication schemes, such as OAuth1, OAuth2, Docker Registry, ElasticSearch, ServiceNow, Splunk and many others. They also serve as an example for writing HTTP connectors to other APIs.

The Secretless Broker is also available as a [Red Hat certified container image](https://catalog.redhat.com/software/containers/search?q=cyberark)

**Review by boazmichaely — APPROVED** [review]
This is my approval for the latest What's New comment at the bottom, thanks

**Review by alexkalish — APPROVED** [review]

**Comment by izgeri** [comment]
@boazmichaely can I suggest we amend your draft with:
```md
Supported Google Cloud services include :

-  Compute Engine
-  Cloud Functions
```

becoming
```md
Supported Google Cloud services include:
-  Compute Engine

**Note**: Support for Cloud Functions is not yet available in this suite release, but will be available in the next suite release.
```

**Comment by boazmichaely** [comment]
> @boazmichaely can I suggest we amend your draft with:
> 
> ```lisp
> Supported Google Cloud services include :
> 
> -  Compute Engine
> -  Cloud Functions
> ```
> 
> becoming
> 
> ```lisp
> Supported Google Cloud services include:
> -  Compute Engine
> 
> **Note**: Support for Cloud Functions is not yet available in this suite release, but will be available in the next suite release.
> ```

@izgeri  drop the future line. How about
```
Supported Google Cloud services at this time include:
 -  Compute Engine

```

**Pull request merged**
