### PR TITLE
Prepare for v1.11.2+suite.1 suite release

### PR DESCRIPTION
**Pull request by izgeri**
### What does this PR do?
Bump suite to v1.11.2+suite.1

Link to gist with draft "What's New" content: https://gist.github.com/izgeri/200953d0792713a3f07c50af229d8e6f

~There is a known bug in #208 that is impacting the release notes that are generated with this release.~

### What ticket does this PR close?
n/a

#### Change log
- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [x] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [x] This PR does not require updating any documentation

#### Release PRs
**If you are preparing for a release**, are the following items complete?
- [x] The PR title / description clearly state the suite release version.
- [x] The [Jenkins dashboard](https://jenkins.conjur.net/view/OSS%20Suite%20Components/) shows no ongoing
      build failures for any included components.
- [x] The PR includes a link to a markdown release notes draft - this can be
     generated by running:
     ```
     summon -p keyring.py   --yaml 'GITHUB_TOKEN: !var github/api_token' \
       ./parse-changelogs \
       -v v1.11.2+suite.1 \
       -t release \
       -o drafts/RELEASE_NOTES.md
     ```
- [x] The PR includes PM-approved "What's new" text.

### CODE REVIEW

**Comment by boazmichaely** [comment]
Please see below  suggested changes.  Compare to [original readme](https://gist.github.com/izgeri/200953d0792713a3f07c50af229d8e6f#whats-new) 

## Reasoning :

1. Mentions of security issues may have legal implications, especially as they could impact Enterprise customers. To avoid exposing CyberArk to legal action we must stick to approved legal verbiage **to the letter**. Not even change "highly recommend" to a bold emphasized "**strongly** recommend"
2. If we're going to mention security fixes up front then we should add a top level section for security fixes under WN, as we do in DAP/PAS release notes . I think that's redundant since there's a security bullet per relevant component.  
3. Combine 1+2 :  in the balance between over communicating to warn our customers (good thing) to risking additional exposure I feel we're better off simply not calling it out under What's New.  
4. Replaced "many bug fixes" with more descriptive text + added a hyperlink
5. I appreciate the desire to plug the API work, but presenting it this way sends a wrong message to our customers (DAP) that the product was not high quality, we're only finding this stuff out now by chance thanks to this work.
With that in mind, the WN of this release may not be the right place to promote future work ? Maybe Discourse instead?

## feedback on changelogs
I only reviewed Conjur changelogs. Generally good, a few escaped, see below.
In addition, here's a thought for future improvement in Changelog:  wouldn't it be great to add links to the relevant end-user documentation where applicable (which is lots of cases)?  I know that our current process does not necessarily support this, if the issue is closed before the doc is published, but as an end user - that's really what I would like to see.  

`Messages for password change now have the field role instead of user under subject cyberark/conjur#2014`
 -- unclear. Which messages? (I see it's about the Log but had to work to find out) ? What is the impact ? Why is this a good thing?

`When batch secret requests are sent with an Accept: base64 header, the secret values in the response will all be Base64-encoded. Sending requests with this header allows users to retrieve binary secrets encoded in Base64. cyberark/conjur#1962`
-- Missing end user context.  What are batch secret requests ? Who is sending to whom and when?
-- Is this really the right reference ([cyberark/conjur#1962](https://github.com/cyberark/conjur/issues/1962)) ? I could not understand how that's related to what is written here
-- Doc link here could really help

`Policy loading no longer fails when attempting to update the annotation search index for a resource that no longer exists. cyberark/conjur#1948`
-- Should this be #1948 or #1949 ?
-- missing end user context. "when attempting to update ..." Who is attempting? What triggers that?  What was the cause and impact of that failure?

`Audit engine routing now correctly matches URLs that include a period (.) in the resource ID. cyberark/conjur#2001`
-- Missing end user context. The issue itself actually gives a good sense of the end user impact, but the changelog does not. Does end user care about the engine?  For auto Changelog to work, we need a mindset switch from editorial comment aimed at internal developers to the end user

`Attempts to retrieve binary secret data in a batch request without using the Accept: base64 header now returns a message explaining that improper secret encoding is the cause of the 500 response. cyberark/conjur#1962`
-- missing context and/or confusion. The issue points to changes made to GO library and the K8s client? Is this a  change to Conjur?  Also , if this is related to changes in  GO and K8s client, wouldn't it be good to cross mention  ?

## shout
I personally enjoy how @izgeri uses free speech to bring to life an otherwise dull list of deprecations 👍 


-- 
  

# Revised What's New :

## What's New

This Suite release aligns with Conjur Server [version 1.11.2](https://github.com/cyberark/conjur/releases/tag/v1.11.2). It includes  [better error handling by the Conjur server ](#cyberarkconjur) and adds the Cloud Foundry integration to the suite. 

For a reminder of the Conjur Open Source Suite Release structure please refer to the documentation [introduction](https://docs.conjur.org/Latest/en/Content/Overview/Conjur-OSS-Suite-Overview.html?#StructureofConjurOpenSourceSuite).

Notable updates are highlighted below.
### Conjur Core

#### Conjur Server

This release includes improved error handling by the Conjur server. 

### Conjur Integrations

#### Conjur Cloud Foundry Integration

In this suite release, the Conjur Cloud Foundry Integration is added to the Conjur OSS Suite! The Cloud Foundry integration includes:
- The Conjur Service Broker to automate provisioning of Conjur identity to applications running in Cloud Foundry, and
- The Conjur Buildpack, which automatically installs a Summon-like binary into your application container when it detects a secrets.yml configuration on application startup, and runs the binary to inject secret values into your application's runtime environment.

Together, these two components make it incredibly easy for your Cloud Foundry-deployed applications to start getting their secrets securely from Conjur, with no code changes!

#### OpenShift Integrations

In this release, Secretless and Secrets Provider both drop support for OpenShift versions 3.9 and 3.10. Secretless adds support for OpenShift 4.3 and 4.5, and Secrets Provider adds support for OpenShift 4.5.

**Comment by izgeri** [comment]
@boazmichaely just wanted to update on the changelog messages:

`Messages for password change now have the field role instead of user under subject cyberark/conjur#2014`
 - This changelog has been removed and moved to the enterprise docs, since the user impact isn't for OSS users. So look forward to this coming back to haunt you when you start reviewing enterprise release notes!

`When batch secret requests are sent with an Accept: base64 header, the secret values in the response will all be Base64-encoded. Sending requests with this header allows users to retrieve binary secrets encoded in Base64. cyberark/conjur#1962`
-- Would this help if we linked to the API docs when we say [batch secret requests](https://docs.conjur.org/Latest/en/Content/Developer/Conjur_API_Batch_Retrieve.htm)? We're referring to an API endpoint in the API changelog.

`Policy loading no longer fails when attempting to update the annotation search index for a resource that no longer exists. cyberark/conjur#1948`
- Should this be #1948 or #1949 ?
   - 1949 is the pull request, 1948 is the issue. It should be 1948
- missing end user context. "when attempting to update ..." Who is attempting? What triggers that?  What was the cause and impact of that failure?
   - The user is loading policy, which causes this. Maybe this should be (cc @h-artzi):
      > Users no longer receive 500 errors when loading policy after performing database backup and restore.

`Audit engine routing now correctly matches URLs that include a period (.) in the resource ID. cyberark/conjur#2001`
- Missing end user context. The issue itself actually gives a good sense of the end user impact, but the changelog does not. Does end user care about the engine?  For auto Changelog to work, we need a mindset switch from editorial comment aimed at internal developers to the end user
   - I agree - let's change this to (cc @micahlee):
     > The audit endpoint no longer incorrectly reports a 404 Not Found response when the resource ID used for retrieving audit events includes a period (.), making it consistent with the other Conjur endpoints.

`Attempts to retrieve binary secret data in a batch request without using the Accept: base64 header now returns a message explaining that improper secret encoding is the cause of the 500 response. cyberark/conjur#1962`
- missing context and/or confusion. The issue points to changes made to GO library and the K8s client? Is this a  change to Conjur?  Also , if this is related to changes in  GO and K8s client, wouldn't it be good to cross mention  ?
   - With this change, we've updated the Conjur API to return a clearer error message when users attempt to send a batch secret retrieval request that includes a secret whose value is binary data. It seems reasonably clear to me.

**Comment by boazmichaely** [comment]
@izgeri thanks !

Q: Would this help if we linked to the API docs when we say batch secret requests? We're referring to an API endpoint in the API changelog.
A: yes, I think so

**Review by alexkalish — DISMISSED** [review]
One minor comment: I noticed that some of the CL log links to files (e.g. `manifeset.yml`, `manifest.txt` are relative, so they didn't work in your Gist.  Will that be a problem when this is published?

**Review by boazmichaely — DISMISSED** [review]

**Comment by izgeri** [comment]
Good catch @alexkalish! I'll fix this in the upstream change logs before merging this PR.

**Comment by izgeri** [comment]
I have to rebase to add in the fixes from #208, but it will not change the contents of the release - so even though it will dismiss your reviews, I am going to proceed with the release.

**Pull request merged**
